# Generated by Django 2.2.6 on 2019-11-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191108_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
