# Generated by Django 3.0.2 on 2020-01-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191125_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usableLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='stack',
            name='studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stack',
            name='stackName',
            field=models.CharField(max_length=50),
        ),
    ]
