# Generated by Django 2.1.1 on 2019-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
