# Generated by Django 2.1.1 on 2019-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0002_tips_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='memo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
