# Generated by Django 2.1.1 on 2019-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0003_tips_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='notic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200, null=True)),
                ('contents', models.CharField(max_length=4000, null=True)),
            ],
        ),
    ]
