# Generated by Django 2.1.1 on 2019-09-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0004_notic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
