# Generated by Django 2.2.6 on 2019-11-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0005_tips_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notic',
            name='contents',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='tips',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tips',
            name='memo',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
