# Generated by Django 2.2.7 on 2019-12-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0006_auto_20191108_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='notic',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tips',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tips',
            name='memo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
