# Generated by Django 3.0 on 2019-12-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0008_heros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heros',
        ),
    ]
