# Generated by Django 3.0.1 on 2020-01-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0010_heros'),
    ]

    operations = [
        migrations.CreateModel(
            name='buff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='debuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DefensePreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Defense', models.IntegerField()),
                ('HP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='epic/image')),
                ('tip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epic7.tips')),
            ],
        ),
    ]
