# Generated by Django 3.0.1 on 2020-01-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0012_auto_20200116_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='imageLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
