# Generated by Django 3.0.1 on 2020-01-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0013_tips_imagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=100)),
                ('UPW', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tips',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='epic/image'),
        ),
    ]
