# Generated by Django 3.0.1 on 2020-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0015_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
