# Generated by Django 3.0.1 on 2020-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0016_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.AddField(
            model_name='user',
            name='Signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
