# Generated by Django 3.0.2 on 2020-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0017_auto_20200116_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='notic',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
