# Generated by Django 3.0.2 on 2020-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0020_botskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='botskills',
            name='target',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
