# Generated by Django 3.0.2 on 2020-01-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic7', '0021_botskills_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
    ]
