# Generated by Django 2.1.1 on 2019-09-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190918_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='context',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='icon',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
