# Generated by Django 2.2.6 on 2019-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190918_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='context',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
