# Generated by Django 2.2.6 on 2019-11-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191106_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='kate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Kategorie'),
        ),
    ]
