# Generated by Django 2.2.6 on 2019-11-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191106_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_img',
            name='projects_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projects'),
        ),
    ]
