# Generated by Django 2.2.6 on 2019-11-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191108_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stackName', models.CharField(max_length=500)),
            ],
        ),
    ]
