# Generated by Django 2.2.7 on 2019-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191119_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
    ]
