# Generated by Django 2.2.7 on 2019-11-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191125_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_img',
            name='img',
            field=models.ImageField(upload_to='home/image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
    ]
