# Generated by Django 3.0.2 on 2020-01-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200120_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stack',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='stackName',
            new_name='skillName',
        ),
    ]
